global:
  trace:
    verbose: true

multiplexer:
  collectors:
    - name: tap
      dnstap:
        listen-ip: 0.0.0.0
        listen-port: 6000

  loggers:
    - name: api
      restapi:
        listen-ip: 0.0.0.0
        listen-port: 8080

  routes:
    - from: [tap]
      to: [api]
