global:
  trace:
    verbose: true

multiplexer:
  collectors:
    - name: tap
      dnstap:
        listen-ip: 0.0.0.0
        listen-port: 6000

  loggers:
    - name: console
      stdout:
        mode: text
    - name: web
      webserver:
        listen-ip: 0.0.0.0
        listen-port: 8080
        top-max-items: 100
        basic-auth-login: admin
        basic-auth-pwd: changeme

  routes:
    - from: [tap]
      to: [console, web]
