version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"

      monitoring:
        patterns:
          - "github.com/prometheus/*"
          - "github.com/grafana/*"

      dmachard:
        patterns:
          - "github.com/dmachard/*"

      other-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
