
global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
      chan-buffer-size: 4096
    routing-policy:
      forward: [ kafka ]
      dropped: []

  - name: kafka
    kafkaproducer:
      remote-address: 192.168.1.16
      remote-port: 9092
      connect-timeout: 5
      retry-interval: 10
      flush-interval: 30
      tls-support: false
      tls-insecure: false
      sasl-support: false
      sasl-mechanism: PLAIN
      sasl-username: false
      sasl-password: false
      mode: flat-json
      buffer-size: 100
      topic: "dnscollector"
      partition: null
      chan-buffer-size: 4096
      compression: none