
before:
  hooks:
    - go mod tidy

builds:
- env:
    - CGO_ENABLED=0

  ldflags:
    - -s -w
    - -X github.com/prometheus/common/version.Version={{.Version}}
    - -X github.com/prometheus/common/version.Revision={{.Commit}}
    - -X github.com/prometheus/common/version.Branch={{.Branch}}
    - -X github.com/prometheus/common/version.BuildDate={{.Date}}

  goos:
    - windows
    - linux
    - darwin
    - freebsd
  goarch:
    - amd64
    - arm64

  # Build reproducible
  mod_timestamp: '{{ .CommitTimestamp }}'

  # Binary name.
  binary: go-dnscollector

archives:
- id: zipformat
  format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
    - config.yml
    
- id: targzformat
  format: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
    - config.yml

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
