################################################
# global configuration
#  more details: https://github.com/dmachard/go-dnscollector/blob/main/docs/configuration.md#global
################################################
global:
  trace:
    verbose: true
  server-identity: "dns-collector"
  text-format: "timestamp-rfc3339ns identity operation rcode queryip queryport family protocol length-unit qname qtype latency"
  text-format-delimiter: " "
  text-format-boundary: "\""

################################################
# Multiplexer configuration
#   more details: https://github.com/dmachard/go-dnscollector/blob/main/docs/running_mode.md#multiplexer
#   collectors: https://github.com/dmachard/go-dnscollector/blob/main/docs/collectors.md
#   loggers: https://github.com/dmachard/go-dnscollector/blob/main/docs/loggers.md
#   transformers: https://github.com/dmachard/go-dnscollector/blob/main/docs/transformers.md
################################################
multiplexer:
  collectors:
    - name: tap
      dnstap:
        listen-ip: 0.0.0.0
        listen-port: 6000
      transforms:
        normalize:
          qname-lowercase: true

  loggers:
    - name: console
      stdout:
        mode: text

  routes:
    - from: [ tap ]
      to: [ console ]

################################################
# Pipelining configuration
#   more details: https://github.com/dmachard/go-dnscollector/blob/main/docs/running_mode.md#pipelining
#   collectors: https://github.com/dmachard/go-dnscollector/blob/main/docs/collectors.md
#   loggers: https://github.com/dmachard/go-dnscollector/blob/main/docs/loggers.md
#   transformers: https://github.com/dmachard/go-dnscollector/blob/main/docs/transformers.md
################################################
# pipelines:
#   - name: main-input
#     dnstap:
#       listen-ip: 0.0.0.0
#       listen-port: 6000
#     routing-policy:
#       default: [ filter ]

#   - name: second-input
#     dnstap:
#       listen-ip: 0.0.0.0
#       listen-port: 6002
#       extended-support: true
#     routing-policy:
#       default: [ console ]

#   - name: filter
#     dnsmessage:
#       matching:
#         include:
#           dns.qname: "^.*\\.google\\.com$"
#     transforms:
#       atags:
#         tags: [ "google"]
#     routing-policy:
#       dropped: [ outputfile ]
#       default: [ central ]

#   - name: central
#     dnstapclient:
#       transport: tcp
#       remote-address: 127.0.0.1
#       remote-port: 6002
#       flush-interval: 5
#       extended-support: true

#   - name: console
#     stdout:
#       mode: flat-json

#   - name: outputfile
#     logfile:
#       file-path:  "/tmp/dnstap.log"
#       max-size: 1000
#       max-files: 10
#       mode: text
