################################################
# global configuration
#  more details: https://github.com/dmachard/go-dnscollector/blob/main/docs/configuration.md#global
################################################
global:
  trace:
    verbose: true
  server-identity: "dns-collector"
  text-format: "timestamp-rfc3339ns identity operation rcode queryip queryport family protocol length-unit qname qtype latency"
  text-format-delimiter: " "
  text-format-boundary: "\""

################################################
# Pipelining configuration
#   more details: https://github.com/dmachard/go-dnscollector/blob/main/docs/running_mode.md#pipelining
#   collectors: https://github.com/dmachard/go-dnscollector/blob/main/docs/collectors.md
#   loggers: https://github.com/dmachard/go-dnscollector/blob/main/docs/loggers.md
#   transformers: https://github.com/dmachard/go-dnscollector/blob/main/docs/transformers.md
################################################
pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    transforms:
      normalize:
        qname-lowercase: true
    routing-policy:
      forward: [ console ]
      dropped: []

  - name: console
    stdout:
      mode: text

################################################
# DEPRECATED - multiplexer configuration
#   more details: https://github.com/dmachard/go-dnscollector/blob/main/docs/running_mode.md#multiplexer
#   collectors: https://github.com/dmachard/go-dnscollector/blob/main/docs/collectors.md
#   loggers: https://github.com/dmachard/go-dnscollector/blob/main/docs/loggers.md
#   transformers: https://github.com/dmachard/go-dnscollector/blob/main/docs/transformers.md
################################################
# multiplexer:
#   collectors:
#     - name: tap
#       dnstap:
#         listen-ip: 0.0.0.0
#         listen-port: 6000
#       transforms:
#         normalize:
#           qname-lowercase: true
#   loggers:
#     - name: console
#       stdout:
#         mode: text
#   routes:
#     - from: [ tap ]
#       to: [ console ]
