global:
  trace:
    verbose: true

multiplexer:
  collectors:
    - name: tap
      dnstap:
        listen-ip: 0.0.0.0
        listen-port: 6000
      transforms:
        normalize:
          qname-lowercase: false

  loggers:
    - name: json
      logfile:
        file-path:  /var/dnscollector/dnstap.log 
        mode: flat-json

    - name: prom
      prometheus:
        listen-ip: 0.0.0.0
        listen-port: 8080

  routes:
    - from: [ tap ]
      to: [ json, prom ]