global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    transforms:
      normalize:
        qname-lowercase: false
        qname-replace-nonprintable: true
    routing-policy:
      forward: [ json, prom ]
      dropped: [ ]

  - name: json
    logfile:
      file-path:  /var/dnscollector/dnstap.log 
      mode: flat-json

  - name: prom
    prometheus:
      listen-ip: 0.0.0.0
      listen-port: 8080