
global:
  trace:
    verbose: true
  telemetry:
    enabled: true
    web-path: "/metrics"
    web-listen: ":9165"
    prometheus-prefix: "dnscollector_exporter"
    tls-support: false
    tls-cert-file: ""
    tls-key-file: ""
    client-ca-file: ""
    basic-auth-enable: false
    basic-auth-login: admin
    basic-auth-pwd: changeme

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      forward: [ prom ]
      dropped: []

  - name: prom
    prometheus:
      listen-ip: 0.0.0.0
      listen-port: 8081
      basic-auth-enable: false
      basic-auth-login: admin
      basic-auth-pwd: changeme
      tls-support: false
      tls-mutual: false
      tls-min-version: 1.2
      cert-file: ""
      key-file: ""
      prometheus-prefix: "dnscollector"
      top-n: 10
      chan-buffer-size: 0
      histogram-metrics-enabled: false
      requesters-metrics-enabled: true
      domains-metrics-enabled: true
      noerror-metrics-enabled: true
      servfail-metrics-enabled: true
      nonexistent-metrics-enabled: true
      timeout-metrics-enabled: true
      prometheus-labels: ["stream_id"]
      requesters-cache-size: 250000
      requesters-cache-ttl: 3600
      domains-cache-size: 500000
      domains-cache-ttl: 3600
      noerror-domains-cache-size: 100000
      noerror-domains-cache-ttl: 3600
      servfail-domains-cache-size: 10000
      servfail-domains-cache-ttl: 3600
      nonexistent-domains-cache-size: 10000
      nonexistent-domains-cache-ttl: 3600
      default-domains-cache-size: 1000
      default-domains-cache-ttl: 3600