# This configuration sets up DNS traffic monitoring through DNStap on port 6000;
# and applies tranformation to reduce qname to lowercase

global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      forward: [ console ]

  - name: console
    stdout:
      mode: text
    transforms:
      normalize:
        qname-lowercase: true