# This configuration sets up DNS traffic monitoring through DNStap on port 6000;
# and save to a file as DNStap 

global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      default: [ dnstap ]

  - name: dnstap
    logfile:
      file-path:  /tmp/dnstap.fstrm
      flush-interval: 10
      mode: dnstap
