# This configuration sets up watch and read PCAP files;
# and logging to the console in JSON format.

global:
  trace:
    verbose: true

pipelines:
  - name: pcap
    file-ingestor:
      watch-dir: /tmp/
      watch-mode: pcap
    transforms:
      normalize:
        qname-lowercase: true
    routing-policy:
      default: [ console ]

  - name: console
    stdout:
      mode: json
