# This configuration sets up DNS traffic monitoring through DNStap on port 6000;
# and log to a remote syslog server with TLS.

global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      forward: [ syslog ]

  - name: syslog
    syslog:
      transport: tcp+tls
      remote-address: "127.0.0.1:6514"
      mode: text
      tls-insecure: true
      formatter: "rfc5424"
      framer: "rfc5425"