# This configuration sets up DNS traffic monitoring through DNStap on port 6000;
# and log the console as PCAP format

global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      forward: [ console ]

  - name: console
    stdout:
      mode: pcap