# This configuration sets up DNS traffic monitoring through DNStap on port 6000
# and logging to a remote Loki server.

global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      default: [ loki ]

  - name: loki
    lokiclient:
      server-url: "http://loki:3100/loki/api/v1/push"
      job-name: "dnscollector"
      text-format: "localtime identity qr queryip family protocol qname qtype rcode"
