# This configuration sets up DNS traffic monitoring through DNStap on port 6000
# and logging in both text and pcap formats.

global:
  trace:
    verbose: true 

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      default: [ text, pcap ]

  - name: text
    logfile:
      file-path:  "/tmp/dnstap.log"
      max-size: 100
      max-files: 10
      mode: text

  - name: pcap
    logfile:
      file-path: "/tmp/dns.pcap"
      mode: pcap