# This configuration sets up DNS traffic monitoring through DNStap on port 6000 and port 6001;
# and logs in text file.

global:
  trace:
    verbose: true

pipelines:
  - name: tap1
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      default: [ file ]

  - name: tap2
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6001
    routing-policy:
      default: [ file ]

  - name: file
    logfile:
      file-path:  "/tmp/dnstap.log"
      max-size: 100
      max-files: 10
      mode: text
