# This configuration sets up DNS traffic monitoring through DNStap on port 6000, 
# and computes Prometheus metrics for analysis.

global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      default: [ prom ]

  - name: prom
    prometheus:
      listen-ip: 0.0.0.0
      listen-port: 8080