# This configuration sets up DNS traffic monitoring through TZSP protocol on port 1000;
# and logging to the console in JSON format.
#
# As prerequisites, we assume you have 
# - a Mikrotik brand device that routes DNS packets and can use the "tzsp" Action in the firewall
# or firewall6 mangle table.


# If turned on, debug messages are printed in the standard output
global:
  trace:
    verbose: true

pipelines:
  - name: tzsp
    tzsp:
        enable: true
        listen-ip: "0.0.0.0"
        listen-port: 10000
    # Redirect output to the console
    routing-policy:
      forward: [ console ]

  - name: console
    stdout:
      mode: json