# This configuration sets up DNS traffic monitoring through DNStap on port 6000 and port 6001;
# applies filtering and save to file

global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    transforms:
      filtering:
        keep-domain-file: ./testsdata/filtering_fqdn.txt
    routing-policy:
      default: [ console ]

  - name: console
    stdout:
      mode: text
