# This configuration sets up DNS traffic monitoring through PowerDNS protobuf on port 6001;
# and transforms it to DNStap on port 6002.

global:
  trace:
    verbose: true

pipelines:
  - name: pdns
    powerdns:
      listen-ip: 0.0.0.0
      listen-port: 6001
    routing-policy:
      forward: [ tap ]

  - name: tap
    dnstapclient:
      remote-address: 127.0.0.1
      remote-port: 6002