# This configuration sets up DNS traffic monitoring through DNStap on port 6000;
# and duplicate the flow to two dnstap receiver

global:
  trace:
    verbose: true

pipelines:
  - name: relay-in
    dnstap-relay:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      default: [ relay-out1, relay-out2 ]

  - name: relay-out1
    dnstapclient:
      remote-address: 127.0.0.1
      remote-port: 6001

  - name: relay-out2
    dnstapclient:
      remote-address: 127.0.0.1
      remote-port: 6002
