
global:
  trace:
    verbose: true

multiplexer:
  collectors:
    - name: tap
      dnstap:
        listen-ip: 0.0.0.0
        listen-port: 6000
  loggers:
    - name: elastic
      elasticsearch:
        server: "http://127.0.0.1:9200/"
        index:  "dnscollector"
        chan-buffer-size: 2048
        bulk-size: 1048576
        flush-interval: 10

  routes:
    - from: [ tap ]
      to: [ elastic ]