
global:
  trace:
    verbose: true

multiplexer:
  collectors:
    - name: tap
      dnstap:
        listen-ip: 0.0.0.0
        listen-port: 6000
        chan-buffer-size: 4096
  loggers:
    - name: elastic
      elasticsearch:
        server: "http://127.0.0.1:9200/"
        index:  "dnscollector"
        chan-buffer-size: 4096
        bulk-size: 5242880
        flush-interval: 5
        compression: gzip
        bulk-channel-size: 10
  routes:
    - from: [ tap ]
      to: [ elastic ]