services:
  dnsdist:
    image: powerdns/dnsdist-21:2.1.1
    container_name: dnsdist
    restart: unless-stopped
    volumes:
      - ./dnsdist.yml:/etc/dnsdist/dnsdist.yml:ro
    command: [ "-C", "/etc/dnsdist/dnsdist.yml" ]
    network_mode: host
    depends_on:
      - dnscollector

  dnscollector:
    container_name: dnscollector
    build:
      context: ../../../
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6000:6000/tcp"
    volumes:
      - ./config.yml:/etc/dnscollector/config.yml:ro
