
global:
  trace:
    verbose: true

pipelines:
  - name: tap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
      chan-buffer-size: 4096
    routing-policy:
      forward: [ fluentd ]
      dropped: []

  - name: fluentd
    fluentd:
      transport: tcp
      remote-address: 127.0.0.1
      remote-port: 24224
      connect-timeout: 5
      retry-interval: 10
      flush-interval: 30
      tag: "dns.collector"
      tls-insecure: false
      tls-min-version: 1.2
      ca-file: ""
      cert-file: ""
      key-file: ""
      buffer-size: 100
      chan-buffer-size: 4096