name: go lint

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        # workaround: when the files to be extracted are already present, tar extraction in Golangci Lint fails with the "File exists"
        # https://github.com/golangci/golangci-lint-action/issues/807
        cache: false

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
        args: --timeout 3m --verbose
 