name: tests powerdns

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    branches:
      - main

permissions:
  contents: read

jobs:

  dnsdist:
    runs-on: ubuntu-22.04
    env:
      COLLECTOR_USER: pdns

    strategy:
      matrix:
        go-version: [ '1.23' ]
        dnsdist: [ '18', '19' ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
        
    - name: build binary
      run: |
        go mod edit -go=${{ matrix.go-version }}
        go mod tidy 
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o go-dnscollector *.go

    - name: Deploy dnsdist docker image
      run: |
        sudo docker run -d --network="host" --name=dnsdist --volume=$PWD/tests/testsdata/powerdns/dnsdist_protobuf.conf:/etc/dnsdist/conf.d/dnsdist.conf:z -v /tmp/:/tmp/ powerdns/dnsdist-${{ matrix.dnsdist }}
        until (dig -p 5553 www.github.com @127.0.0.1 | grep NOERROR); do sleep 5.0; done

    - name: Test dns query
      run: |
        sudo python3 -m pip install dnspython
        sudo -E python3 -m unittest tests.dnsquery_powerdns -v

  recursor:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        go-version: [ '1.23' ]
        recursor: [ '49', '50' ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: build binary
      run: |
        go mod edit -go=${{ matrix.go-version }}
        go mod tidy 
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o go-dnscollector *.go

    - name: Deploy recursor docker image
      run: |
        sudo docker run -d --network="host" --name=recursor --volume=$PWD/tests/testsdata/powerdns/pdns_recursor.lua:/etc/powerdns/recursor.lua:z --volume=$PWD/tests/testsdata/powerdns/pdns_recursor.conf:/etc/powerdns/recursor.conf:z powerdns/pdns-recursor-${{ matrix.recursor }}
        until (dig -p 5553 www.github.com @127.0.0.1 | grep NOERROR); do sleep 5.0; done

    - name: Test send query
      run: |
        sudo python3 -m pip install dnspython
        sudo -E python3 -m unittest tests.dnsquery_powerdns -v

  recursor5:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        go-version: [ '1.23' ]
        recursor: [ '51' ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: build binary
      run: |
        go mod edit -go=${{ matrix.go-version }}
        go mod tidy 
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o go-dnscollector *.go

    - name: Deploy recursor 5.x docker image
      run: |
        sudo docker run -d --network="host" --name=recursor --volume=$PWD/tests/testsdata/powerdns/pdns_recursor.yml:/etc/powerdns/recursor.yml:z powerdns/pdns-recursor-${{ matrix.recursor }}
        until (dig -p 5553 www.github.com @127.0.0.1 | grep NOERROR); do sleep 5.0; done

    - name: Test send query
      run: |
        sudo python3 -m pip install dnspython
        sudo -E python3 -m unittest tests.dnsquery_powerdns -v